os:
  - linux
  - osx
language: c
dist: trusty
sudo: required
env:
  - EMULATOR=simh BASICS=yes TIMEOUT=100
  - EMULATOR=klh10 BASICS=yes TIMEOUT=100
  - EMULATOR=pdp10-ka BASICS=yes TIMEOUT=100
  - EMULATOR=pdp10-kl BASICS=yes TIMEOUT=100
matrix:
  exclude:
    - os: osx
      env: EMULATOR=klh10 BASICS=yes
    - os: osx
      env: EMULATOR=pdp10-ka BASICS=yes
    - os: osx
      env: EMULATOR=pdp10-kl BASICS=yes
install: sh -ex build/dependencies.sh install_${TRAVIS_OS_NAME:-linux}
script: make check-dirs all
notifications:
  email: lars@nocrew.org
